##
## Entangle deployment relay profile for strfry
##

db = "/app/strfry-db/"

relay {
    bind = "0.0.0.0"
    port = 7777
    nofiles = 0

    auth {
        enabled = false
        serviceUrl = ""
    }

    info {
        name = "Entangle Relay"
        description = "Federated dev strfry relay profile for Entangle development."
        pubkey = ""
        self = ""
        contact = ""
        icon = ""
        banner = ""
        privacy = ""
        terms = ""
        nips = ""
    }
}
